import '../models/hospital.dart';
import '../models/ambulance.dart';
import '../models/audit_log.dart';
import '../models/volunteer_model.dart';
import '../models/transfer_request.dart';
import '../models/community_need.dart';

class MockData {
  static List<Hospital> get hospitals => [
        const Hospital(
          id: 'h1',
          name: 'Sanjivani Specialty Hospital',
          beds: 138,
          icuBeds: 7,
          ventilators: 12,
          pediatricBeds: 10,
          traumaBeds: 5,
          oxygen: 350,
          latitude: 12.9716,
          longitude: 77.5946,
          city: 'Bengaluru',
          tier: 'MEDIUM',
        ),
        const Hospital(
          id: 'h2',
          name: 'St. Bridget Medical Center',
          beds: 45,
          icuBeds: 3,
          ventilators: 4,
          pediatricBeds: 6,
          traumaBeds: 2,
          oxygen: 80,
          latitude: 12.9352,
          longitude: 77.6245,
          nodeType: 'ngo',
          city: 'Bengaluru',
          tier: 'SMALL',
        ),
        const Hospital(
          id: 'h3',
          name: 'Lakshmi Global Hospital',
          beds: 280,
          icuBeds: 22,
          ventilators: 30,
          pediatricBeds: 40,
          traumaBeds: 15,
          oxygen: 600,
          latitude: 12.9801,
          longitude: 77.5872,
          city: 'Bengaluru',
          tier: 'LARGE',
        ),
        const Hospital(
          id: 'h4',
          name: 'North Arc Care Hospital',
          beds: 90,
          icuBeds: 8,
          ventilators: 10,
          pediatricBeds: 12,
          traumaBeds: 6,
          oxygen: 220,
          latitude: 12.9900,
          longitude: 77.5700,
          city: 'Bengaluru',
          tier: 'MEDIUM',
        ),
        const Hospital(
          id: 'h5',
          name: 'Ridgeview Community Hospital',
          beds: 30,
          icuBeds: 2,
          ventilators: 2,
          pediatricBeds: 4,
          traumaBeds: 1,
          oxygen: 60,
          latitude: 12.9500,
          longitude: 77.6100,
          nodeType: 'community_hub',
          city: 'Bengaluru',
          tier: 'SMALL',
        ),
      ];

  static List<Ambulance> get ambulances => [
        Ambulance(
          id: 'a1',
          fromHospitalId: 'h3',
          fromHospitalName: 'Lakshmi Global',
          toHospitalId: 'h1',
          toHospitalName: 'Sanjivani Specialty',
          patientType: PatientType.icu,
          status: AmbulanceStatus.enRoute,
          eta: DateTime.now().add(const Duration(minutes: 12)),
          dispatchedAt: DateTime.now().subtract(const Duration(minutes: 5)),
        ),
        Ambulance(
          id: 'a2',
          fromHospitalId: 'h4',
          fromHospitalName: 'North Arc Care',
          toHospitalId: 'h2',
          toHospitalName: 'St. Bridget Medical',
          patientType: PatientType.general,
          status: AmbulanceStatus.enRoute,
          eta: DateTime.now().add(const Duration(minutes: 5)),
          dispatchedAt: DateTime.now().subtract(const Duration(minutes: 2)),
        ),
      ];

  static List<Volunteer> get volunteers => [
        const Volunteer(
          id: 'v1',
          name: 'Aditi Rao',
          vehicleType: 'Van',
          latitude: 12.9720,
          longitude: 77.5950,
          status: VolunteerStatus.available,
          capacityKg: 500,
          phone: '+91 90000 11001',
        ),
        const Volunteer(
          id: 'v2',
          name: 'Imran Khan',
          vehicleType: 'Sedan',
          latitude: 12.9360,
          longitude: 77.6250,
          status: VolunteerStatus.available,
          capacityKg: 100,
          phone: '+91 90000 11002',
        ),
        const Volunteer(
          id: 'v3',
          name: 'Meera Nair',
          vehicleType: 'Pickup',
          latitude: 12.9810,
          longitude: 77.5880,
          status: VolunteerStatus.enRoute,
          capacityKg: 800,
          phone: '+91 90000 11003',
        ),
        const Volunteer(
          id: 'v4',
          name: 'Ravi Kumar',
          vehicleType: 'Van',
          latitude: 12.9700,
          longitude: 77.6000,
          status: VolunteerStatus.available,
          capacityKg: 450,
          phone: '+91 90000 11004',
        ),
        const Volunteer(
          id: 'v5',
          name: 'Sneha Patil',
          vehicleType: 'Sedan',
          latitude: 12.9300,
          longitude: 77.6200,
          status: VolunteerStatus.unavailable,
          capacityKg: 120,
          phone: '+91 90000 11005',
        ),
        const Volunteer(
          id: 'v6',
          name: 'Deepak Menon',
          vehicleType: 'Pickup',
          latitude: 12.9750,
          longitude: 77.5900,
          status: VolunteerStatus.available,
          capacityKg: 750,
          phone: '+91 90000 11006',
        ),
      ];

  static List<TransferRequest> get transferRequests => [
        const TransferRequest(
          id: 'tr1',
          resourceType: 'OXYGEN',
          status: TransferRequestStatus.pending,
          fromName: 'Lakshmi Global Hospital',
          toName: 'St. Bridget Medical Center',
          quantity: 300,
        ),
        const TransferRequest(
          id: 'tr2',
          resourceType: 'OXYGEN',
          status: TransferRequestStatus.pending,
          fromName: 'Lakshmi Global Hospital',
          toName: 'Ridgeview Community Hospital',
          quantity: 300,
        ),
      ];

  // ── Community Needs — the "scattered field data" from the problem statement
  static List<CommunityNeed> get communityNeeds => [
        CommunityNeed(
          id: 'cn1',
          title: '15 elderly need oxygen cylinders',
          description: 'KR Market slum area — 15 elderly residents with chronic respiratory issues need portable oxygen. Nearest clinic is 4km away.',
          reportedBy: 'Southside NGO Care Center',
          area: 'KR Market, Ward 12',
          category: 'healthcare',
          urgency: NeedUrgency.critical,
          reportedAt: DateTime.now().subtract(const Duration(hours: 1)),
        ),
        CommunityNeed(
          id: 'cn2',
          title: 'Free eye screening camp needed',
          description: '200+ residents in Jayanagar 4th Block have no access to ophthalmology. Lions Club survey identified 40 cataract-stage cases.',
          reportedBy: 'Lions Club Bengaluru',
          area: 'Jayanagar 4th Block',
          category: 'healthcare',
          urgency: NeedUrgency.high,
          reportedAt: DateTime.now().subtract(const Duration(hours: 3)),
        ),
        CommunityNeed(
          id: 'cn3',
          title: '40 families need clean drinking water',
          description: 'Borewell contamination in Koramangala 6th Block. 40 families affected. Paper survey collected door-to-door by field workers.',
          reportedBy: 'WaterAid Field Team',
          area: 'Koramangala 6th Block',
          category: 'resources',
          urgency: NeedUrgency.critical,
          reportedAt: DateTime.now().subtract(const Duration(minutes: 45)),
        ),
        CommunityNeed(
          id: 'cn4',
          title: 'Post-flood medical camp — Yelahanka',
          description: 'Recent flooding displaced 80 families. 12 children showing symptoms of waterborne disease. Need mobile medical unit.',
          reportedBy: 'Red Cross Bengaluru',
          area: 'Yelahanka New Town',
          category: 'healthcare',
          urgency: NeedUrgency.critical,
          reportedAt: DateTime.now().subtract(const Duration(minutes: 20)),
        ),
        CommunityNeed(
          id: 'cn5',
          title: 'Wheelchair & mobility aids for 8 seniors',
          description: 'Aged care home in BTM Layout needs 8 wheelchairs. Current ones are broken. Reported via paper form to local ward office.',
          reportedBy: 'BTM Senior Care Trust',
          area: 'BTM Layout 2nd Stage',
          category: 'resources',
          urgency: NeedUrgency.medium,
          reportedAt: DateTime.now().subtract(const Duration(hours: 6)),
        ),
        CommunityNeed(
          id: 'cn6',
          title: 'Blood donation drive volunteers needed',
          description: 'Sanjivani Hospital blood bank running critically low on O- and B+ types. Need 20 volunteers for emergency donation camp.',
          reportedBy: 'Sanjivani Hospital',
          area: 'Rajajinagar',
          category: 'healthcare',
          urgency: NeedUrgency.high,
          reportedAt: DateTime.now().subtract(const Duration(hours: 2)),
        ),
        CommunityNeed(
          id: 'cn7',
          title: 'Nutrition kits for 60 malnourished children',
          description: 'ICDS survey in Whitefield slum found 60 children under 5 with severe malnutrition. Need ready-to-eat therapeutic food packets.',
          reportedBy: 'ICDS Whitefield Center',
          area: 'Whitefield Slum Area',
          category: 'food',
          urgency: NeedUrgency.high,
          reportedAt: DateTime.now().subtract(const Duration(hours: 4)),
        ),
        CommunityNeed(
          id: 'cn8',
          title: 'Temporary shelter for 25 migrant workers',
          description: 'Construction site shut down. 25 workers stranded without shelter. Community volunteer survey filed with ward office.',
          reportedBy: 'Migrant Workers Union',
          area: 'Electronic City Phase 2',
          category: 'shelter',
          urgency: NeedUrgency.high,
          reportedAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 30)),
        ),
        CommunityNeed(
          id: 'cn9',
          title: 'First-aid training for slum community',
          description: 'Dharavi Bengaluru chapter — 3 snakebite cases last month. Community leaders requesting first-aid awareness volunteers.',
          reportedBy: 'Community Health Workers',
          area: 'Majestic Area',
          category: 'healthcare',
          urgency: NeedUrgency.medium,
          reportedAt: DateTime.now().subtract(const Duration(hours: 8)),
        ),
        CommunityNeed(
          id: 'cn10',
          title: 'Sanitary pad distribution — 200 girls',
          description: 'Government school in Peenya reports 200 girls missing school days. NGO paper survey confirmed menstrual hygiene gap.',
          reportedBy: 'She Wings Foundation',
          area: 'Peenya Industrial Area',
          category: 'resources',
          urgency: NeedUrgency.medium,
          reportedAt: DateTime.now().subtract(const Duration(hours: 5)),
        ),
      ];

  static List<AuditLog> get auditLogs => [
        AuditLog(
          id: 'l1',
          userId: 'mock-admin',
          action: 'transfer',
          fromHospitalId: 'h3',
          fromHospitalName: 'Lakshmi Global',
          toHospitalId: 'h2',
          toHospitalName: 'St. Bridget Medical',
          resourceType: 'beds',
          amount: 5,
          fromBefore: 50,
          fromAfter: 45,
          toBefore: 0,
          toAfter: 5,
          timestamp: DateTime.now().subtract(const Duration(hours: 2)),
        ),
      ];
}
