 // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALuYI4UVj3ZKzNQj8cAxhkBraIsZJ72Mg',
    appId: '1:343177205461:web:f34761596e516e06e0345c',
    messagingSenderId: '343177205461',
    projectId: 'medilinkai-3280e',
    authDomain: 'medilinkai-3280e.firebaseapp.com',
    storageBucket: 'medilinkai-3280e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALuYI4UVj3ZKzNQj8cAxhkBraIsZJ72Mg',
    appId: '1:343177205461:web:d8eeb12c3b5c06b7e0345c',
    messagingSenderId: '343177205461',
    projectId: 'medilinkai-3280e',
    authDomain: 'medilinkai-3280e.firebaseapp.com',
    storageBucket: 'medilinkai-3280e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfM3uxy9T_HQ2mmB4XTvcGQeaBWCWQGd0',
    appId: '1:343177205461:ios:b41996b565fe261fe0345c',
    messagingSenderId: '343177205461',
    projectId: 'medilinkai-3280e',
    storageBucket: 'medilinkai-3280e.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfM3uxy9T_HQ2mmB4XTvcGQeaBWCWQGd0',
    appId: '1:343177205461:ios:b41996b565fe261fe0345c',
    messagingSenderId: '343177205461',
    projectId: 'medilinkai-3280e',
    storageBucket: 'medilinkai-3280e.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLEWumYd6PwW52_pqIYQi6V-alPSZQF4',
    appId: '1:343177205461:android:3c55f9b84541952be0345c',
    messagingSenderId: '343177205461',
    projectId: 'medilinkai-3280e',
    storageBucket: 'medilinkai-3280e.firebasestorage.app',
  );

}
